import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";
import {notFound} from "next/navigation";
import {routing} from "@/i18n/routing";
import localFont from "next/font/local";
import "../globals.css";
import {Roboto} from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto"
});

const iranSansX = localFont({
  src: [
    {
      path: "../../public/fonts/IRANSansXV.woff",
      weight: "100 300 400 500 700 900",
      style: "normal"
    }
  ],
  variable: "--font-iransansx"
});

export const metadata = {
  title: "parsian cargo",
  description: "Generated by create next app"
};

export default async function LocaleLayout({children, params: locale}) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`${roboto.className} ${iranSansX.className} `}>
        <NextIntlClientProvider messages={messages}>
          <Navbar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
