import {NextIntlClientProvider} from "next-intl";
import {getMessages} from "next-intl/server";
import {notFound} from "next/navigation";
import {routing} from "@/i18n/routing";
import localFont from "next/font/local";
import "../globals.css";
import {Roboto} from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import {NextAuthProvider} from "@/context/NextAuthProvider";
import {QueryProvider} from "@/context/QueryProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto"
});

const iranSansX = localFont({
  src: [
    {
      path: "../../public/fonts/IRANSansXV.woff",
      weight: "100 300 400 500 700 900",
      style: "normal"
    }
  ],
  variable: "--font-iransansx"
});

export const metadata = {
  title: "پیام کارگو",
  description: "Generated by create next app"
};

export default async function LocaleLayout({children, params}) {
  // استخراج locale از params
  const locale = params.locale;

  // اعتبارسنجی locale
  if (!locale || !routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`${roboto.className} ${iranSansX.className}`}>
        <NextAuthProvider>
          <QueryProvider>
            <NextIntlClientProvider messages={messages}>
              <Navbar />
              {children}
              <Footer />
            </NextIntlClientProvider>
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
